<div id="credential-bpay" class="hide">
    <div class="control-group">
        <label class="control-label control-listed">BPAY details:</label>
        <div class="controls">
            <span class="payment-details-bpay pull-left"></span>
            <div class="payment-details pull-left">
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="property">Biller Code:</td>
                        <td>868372</td>
                    </tr>
                    <tr>
                        <td class="property">Customer Ref:</td>
                        <td>700814263617</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="controls">
            <p class="payment-details control-block grid field-12">
                To make your payment by BPAY, simply complete your application and then have your bank/financial institution process this payment from your cheque, debit,
                credit card or transaction account using the billing information above. This information will also be sent to you by email once your application is complete.
            </p>
        </div>
    </div>
</div>