<div id="credential-paypal" <?php echo $this->paypal_hide; ?>>
    <div class="control-group">
        <label class="control-label control-listed">Paypal payment details:</label>
        <div class="controls">
            <p class="paypal-details control-block grid field-12">
                To make your payment using Paypal, you will be redirected to a separate page to complete your payment credentials and your purchase transaction.
            </p>
        </div>
    </div>
</div>