<div id="credential-paypal" <?php echo $this->paypal_hide; ?>>
    <div class="control-group">
        <label class="control-label control-listed">Paypal payment details:</label>
        <div class="controls">
            <p class="paypal-details control-block grid field-12">
                You have successfully authorized your Paypal credentials. Please click the "Confirm Payment" button below to finish your Paypal payment transaction.
            </p>
        </div>
    </div>
</div>