<?php
/**
 * Processing Prompt for Payment
 * 
 * @package     Business Name
 * @subpackage  BN Registration
 * @category    View
 * @version     1.0
 * @copyright   (c) 2013, Business Switch Pty Ltd
 * @author      Bien Angelo Relucano <bien.relucano@business-switch.com.au>,
 * @created		02 May 2013
 */
?>
<section class="modal-content">
	<div class="modal-process">
		<img alt="processing" src="assets/img/processing.gif">
		<h1 class="success">Payment successful<span></span></h1>
		<h1 class="processing">Processing business name lodging...<span></span></h1>
		<h1 class="error">Failed sending invoice (.error)<span></span></h1>
		<h1 class="warning">Failed sending invoice (.warning)<span></span></h1>
		<h1 class="pending">Send invoice (.pending)<span></span></h1>
	</div>
	<div class="modal-info">
		<p>
			Please do not close this window. We are currently submitting your business name application to the Australian Securities & Investments Commission 
			and this process can take some time. You will also receive an email from us with the status of your application within the next 20 minutes. 
		</p>
	</div>
</section>
<?php
/* End of file processing.phtml */
/* Location: ./module/Payment/view/payment/messages/processing.phtml */