<?php

/**
 * Pending Prompt for Payment
 * 
 * @package     Business Name
 * @subpackage  BN Registration
 * @category    View
 * @version     1.0
 * @copyright   (c) 2013, Business Switch Pty Ltd
 * @author      Bien Angelo Relucano <bien.relucano@business-switch.com.au>,
 * @created		06 May 2013
 */
?>
<section class="form-content prompt">
	<div class="container form-block">
		<div class="pending-prompt">
			<img alt="Payment Pending" src="/assets/img/icons/large-tick.png"/>
			<h1>Your application is almost done!</h1>
			<p>Kindly settle your payment within <strong>7 days.</strong> </p>
			<div class="success-info">
				<p>
					You will receive an email with the details of your order and the payment instructions for your application. <br/>
					Once completed, we will process your registration. You can now exit this window or <a href="/">click here</a> to register another ABN. 
				</p>
			</div>
		</div>
	</div>
</section>
<!-- Google Code for BusinessName Conversion Page -->
<script type="text/javascript">
	/* <![CDATA[ */
	var google_conversion_id = 1017581591;
	var google_conversion_language = "en";
	var google_conversion_format = "3";
	var google_conversion_color = "ffffff";
	var google_conversion_label = "5sl5CKGfxgQQl6Cc5QM";
	var google_conversion_value = 0;
	/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
<div style="display:inline;">
	<img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/1017581591/?value=0&amp;label=5sl5CKGfxgQQl6Cc5QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<?php
/* End of file payment-pending.phtml */
/* Location: ./module/Payment/view/payment/messages/payment-pendinga.phtml */