<?php

/**
 * Success Prompt for Payment
 * 
 * @package     Tax File Number
 * @subpackage  Tax File Number
 * @category    View
 * @version     1.0
 * @copyright   (c) 2013, Business Switch Pty Ltd
 * @author      Michael Caringal <michael.caringal@business-switch.com.au>,
 * @modified    Chris Loria <christian.loria@business-switch.com.au>,
 * @created     24 September 2013
 * @modified    26 September 2013
 */

$title = 'Success';
$this->headTitle($title);

?>

<section id="error-main">
    <h1> Thank you for your payment! </h1>
    <figure>
        <figcaption>
            <h2>Your transaction has been completed and a receipt for your purchase has been emailed to you. Your application has been lodged and we will be in touch shortly with more information regarding your order.</h2>
        </figcaption>
        
    </figure>
</section><!--main-->

<!-- Google Code for TFN conversion page Remarketing List -->
<script type="text/javascript"> 
/* <![CDATA[ */
 var google_conversion_id = 1017581591; 
 var google_conversion_language = "en"; 
 var google_conversion_format = "3"; 
 var google_conversion_color = "ffffff"; 
 var google_conversion_label = "fe7rCKHljQMQl6Cc5QM"; 
 var google_conversion_value = 0; 
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
  <div style="display:inline;"> 
    <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1017581591/?label=fe7rCKHljQMQl6Cc5QM&amp;guid=ON&amp;script=0"/> 
  </div> 
</noscript>
 <!-- Google Code for TFN Sales Conversion Page -->
<script type="text/javascript"> 
/* <![CDATA[ */ 
  var google_conversion_id = 1017581591; 
  var google_conversion_language = "en"; 
  var google_conversion_format = "3"; 
  var google_conversion_color = "ffffff"; 
  var google_conversion_label = "VOvPCJGcjQMQl6Cc5QM"; 
  var google_conversion_value = 0; 
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
  <div style="display:inline;"> 
    <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1017581591/?label=VOvPCJGcjQMQl6Cc5QM&amp;guid=ON&amp;script=0"/> 
  </div> 
</noscript>
  
<?php
/* End of file success.phtml */
/* Location: ./module/Payment/view/payment/messages/success.phtml */